### ISSUE TITLE
Missing Files Error During Training

### ISSUE THREAD

**Issue by Zavianx** [KumapowerLIU/HeadArtist#3]
Hi，
Thanks for your excellent work. However, when I run the training command python launch.py configs/headartist-geometry.yaml --train --gpu 0 system.prompt_processor.prompt="a DSLR portrait of an elderly woman with deep wrinkles, wearing a knitted hat, photorealistic, flawless face", it says it cannot find head_sdf_network.pth and head_encoding.pth.
Zhongan

**Comment by KumapowerLIU** [comment]
Sorry, I forgot to upload these two files before. And these two files at './load/headartist' now.
